config/routes.rb
Rails.application.routes.draw do
  root to: 'childlogs#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]

  resources :childlogs
  resources :children
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :user
  
    validates :childname, presence: true, length: { maximum: 50 }
    validates :childbirthday, presence: true, length: { maximum: 10 }

  has_many :childlogs
  
  def age
   date_format = "%Y%m%d"
   (Date.today.strftime(date_format).to_i - childbirthday.strftime(date_format).to_i) / 10000
  end
  
end

app/models/childlog.rb
class Childlog < ApplicationRecord
    
    validates :word, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 255 }
    validates :childwordtiming, presence: true, length: { maximum: 10 }


    belongs_to :user
    belongs_to :child
    
  def childwordage
   date_format = "%Y%m%d"
   (childwordtiming.strftime(date_format).to_i - childlog.child.childbirthday.strftime(date_format).to_i) / 10000
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :childlogs
  has_many :children  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper


  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/childlogs_controller.rb
class ChildlogsController < ApplicationController
  before_action :require_user_logged_in, except: [:index]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    if logged_in?
      @childlog = current_user.childlogs.build  # form_for 用
      @childlogs = current_user.childlogs.order('created_at DESC').page(params[:page])
    end
  end

  def show
    @childlog = Childlog.find(params[:id])
  end

  def new
    @childlog = Childlog.new
  end
  
  def create
    @childlog = current_user.childlogs.build(childlog_params)
    
    if @childlog.save
      flash[:success] = '新しいことばが正常に投稿されました'
      redirect_to @childlog
    else
      current_user.childlogs.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '新しいことばが投稿されませんでした'
      render :new
    end
  end

  def edit
    @childlog = Childlog.find(params[:id])
  end
  
  def update
    @childlog = Childlog.find(params[:id])

    if @childlog.update(childlog_params)
      flash[:success] = '正常に更新されました'
      redirect_to @childlog
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @childlog = Childlog.find(params[:id])
    @childlog.destroy

    flash[:success] = '正常に削除されました'
    redirect_to childlogs_url
  end
  
  private
  
   def set_childlog
    @Childlog = Childlog.find(params[:id])
   end
  
  def correct_user
    @childlog = current_user.childlogs.find_by(id: params[:id])
    unless @childlog
      redirect_to root_url
    end
  end

  # Strong Parameter
  def childlog_params
    params.require(:childlog).permit(:word, :content, :childwordtiming, :child_id)
  end
  
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController

  def index
    if logged_in?
      @child = current_user.children.build  # form_for 用
      @children = current_user.children.order('created_at DESC').page(params[:page])
    end
  end

  def show
    @child = Child.find(params[:id])
  end

  def new
    @child = Child.new
  end

  def create
    @child = current_user.children.build(child_params)

    if @child.save
      flash[:success] = 'こども情報を登録しました。'
      redirect_to @child
    else
      current_user.children.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'こども情報の登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @child = Child.find(params[:id])
  end
  
  def update
    @child = Child.find(params[:id])

    if @child.update(child_params)
      flash[:success] = '正常に更新されました'
      redirect_to @child
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    flash[:success] = '正常に削除されました'
    redirect_to children_url
  end  

  private
  
   def set_child
    @Child = Child.find(params[:id])
   end
  
  def correct_user
    @child = current_user.child.find_by(id: params[:id])
    unless @child
      redirect_to root_url
    end
  end

  # Strong Parameter
  def child_params
    params.require(:child).permit(:childname, :childbirthday)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました！'
      redirect_to childlogs_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました！'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @childlog = current_user.childlogs.build  # form_for 用
      @childlogs = current_user.childlogs.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @childlogs = @user.childlogs.order('created_at DESC').page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/childlogs_helper.rb
module ChildlogsHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/childlogs/_childlogs.html.erb
<ul class="media-list">
  <% childlogs.each do |childlog| %>
    <li class="media">
      <div class="media-body">
        <div>
          <%= link_to childlog.user.name, user_path(childlog.user) %> <span class="text-muted">posted at <%= childlog.created_at %></span>
        </div>
        <div>
          <p><%= childlog.content %></p>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate childlogs %>
</ul>

app/views/childlogs/_form.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6 col-sm-offset-2 col-sm-8 col-xs-12">

<%= form_for(childlog) do |f| %>
  <% if childlog.errors.any? %>
    <div class="alert alert-warning">
      <ul>
        <% childlog.errors.full_messages.each do |childlog| %>
          <li><%= childlog %></li>
        <% end %>
      </ul>
    </div>
<% end %>

  <div class="form-group">
    <%= f.label :title, 'ことば' %>
    <%= f.text_field :word, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content, 'ことばの詳細' %>
    <%= f.text_area :content, rows:5, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :childwordtiming, 'ことばを発した日' %>
    <%= f.date_field :childwordtiming, rows:5, class: 'form-control date-picker' %>
  </div>
  
  <div class="form-group">
    <%= f.label :child, 'こども' %><BR>
    <%= f.collection_select(:child_id, current_user.children, :id, :childname, :prompt => "選択してください")%>
  </div>

  <%= f.submit '更新', class: 'btn btn-primary' %>
  <%= link_to 'ことば一覧に戻る', childlogs_url , class: 'btn btn-default'%> 
  <% end %>
  </div>
</div>

app/views/childlogs/edit.html.erb
<div class="pagetitle">
  <h1 align="center">ことばの編集</h1>
</div>

<%= render 'form', childlog: @childlog %>

app/views/childlogs/index.html.erb
<% if logged_in? %>
  
  <div class="pagetitle">
    <p><h2 align="center">ことば一覧</h2></p>
    <p><h3 align="center">- STEP.1 こども情報を登録してね → STEP.2 ことばを登録してね -</h3></p>
  </div>
  
  <% if @childlogs.any? %>
    <table class="table table-hover">
      <thead.thead-default>
        <tr>
          <th><h5>ことば</h5></th>
          <th><h5>ことばの詳細</h5></th>
          <th><h5>だれのことば</h5></th>
          <th><h5>ことばを発した日</h5></th>
          <th><h5>ことばを発した年齢</h5></th>          
          <th><h5>登録日時</h5></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @childlogs.each do |childlog| %>
          <tr>
            <td><h5><%= link_to childlog.word.truncate(10, omission: '…'), childlog %></h5></td>
            <td><h5><%= childlog.content.truncate(10, omission: '…') %></h5></td>
            <td><h5><%= childlog.child.childname %></h5></td>            
            <td><h5><%= childlog.childwordtiming %></h5></td>
            <td><h5><%= (childlog.childwordtiming.strftime('%Y%m%d').to_i - childlog.child.childbirthday.strftime('%Y%m%d').to_i) / 10000  %>歳</h5></td>            
            <td><h5><%= childlog.created_at.strftime('%Y-%m-%d %H:%M') %></h5></td>
            <td><%= link_to '編集', edit_childlog_path(childlog), class: "btn btn-primary" %></td>
            <td><%= link_to '削除', childlog, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-warning' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  
  <%= link_to 'ことば登録', new_childlog_path, class: "btn btn-primary" %>
<% else %>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 cover-img" style="background-image:url('/images/park_photo3.jpg');">
		<div class="col-xs-12 cover-mask";">			
			<div class="cover-text text-center">
			  <div class="pagetitle">
				<p><h1 style="color: #646766;">こどもログとは？</h1></p>
				<p><h3 style="color: #646766;">小さなこどもの言い間違いなど、こどもの言葉をログとして登録できるサイトです</h3><p>
				<p><h3 style="color: #646766;">例：とうもころし -> とうもろこしのこと</h3><p>
				</div>
				
				<BR>
				  <%= link_to 'ユーザー登録はこちらです', signup_path, class: 'btn btn-lg btn-info' %>
			</div>
		</div>
	</div>

</div>
<% end %>

app/views/childlogs/new.html.erb
<div class="pagetitle">
  <p><h2 align="center">ことば登録</h2></p>
  <p><h3 align="center">- ことばや発した日、誰が発したかを登録してね -</h3></p>
</div>

<%= render 'form', childlog: @childlog %>

app/views/childlogs/show.html.erb
<div class="pagetitle">
  <h2 align="center">ことばの詳細</h2>
</div>

<table class="table table-hover">
    <thead.thead-default>
  <tr>
    <th><h4>ことば</h4></th>
    <td><h4><%= @childlog.word %></h4></td>
  </tr>
  <tr>
    <th><h4>ことばの詳細</h4></th>
    <td><h4><%= @childlog.content %></h3></td>
  </tr>
    <tr>
    <th><h4>だれのことば</h4></th>
    <td><h4><%= @childlog.child.childname %></h4></td>
  </tr>  
  <tr>
  <tr>
    <th><h4>ことばを発した日</h4></th>
    <td><h4><%= @childlog.childwordtiming %></h4></td>
  </tr>  
  <tr>
    <th><h4>登録日時</h4></th>
    <td><h4><%= @childlog.created_at.strftime('%Y-%m-%d %H:%M') %></h4></td>
  </tr>
  <tr>
    <th><h4>更新日時</h4></th>
    <td><h4><%= @childlog.updated_at.strftime('%Y-%m-%d %H:%M') %></h4></td>
  </tr>
</table>

<%= link_to '編集', edit_childlog_path(@childlog), class: 'btn btn-primary' %>
<%= link_to '削除', @childlog, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-warning' %>
<%= link_to 'ことば一覧に戻る', childlogs_url , class: 'btn btn-default'%> 

app/views/children/create.html.erb
<h1>Children#create</h1>
<p>Find me in app/views/children/create.html.erb</p>

app/views/children/edit.html.erb
<div class="pagetitle">
  <h2 align="center">こども情報の編集</h2>
</div>

<div class="row">
  <div class="col-lg-offset-3 col-lg-6 col-sm-offset-2 col-sm-8 col-xs-12">

<%= form_for(@child) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :childname, 'ニックネーム' %>
    <%= f.text_field :childname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :childbirthday, '誕生日' %>
    <%= f.date_field :childbirthday,class: 'form-control' %>
  </div>

  <%= f.submit '更新', class: 'btn btn-primary' %>
  <%= link_to 'こども一覧に戻る', children_url , class: 'btn btn-default'%> 
  <% end %>
  </div>
</div>

app/views/children/index.html.erb
  <div class="pagetitle">
    <p><h2 align="center">こども一覧</h2></p>
    <p><h3 align="center">- 登録したこどもの情報一覧だよ -</h3></p>
  </div>

  <% if @children.any? %>
    <table class="table table-hover">
      <thead.thead-default>
        <tr>
          <th><h4>ニックネーム</h4></th>
          <th><h4>誕生日</h4></th>
          <th><h4>年齢</h4></th>          
          <th><h4>登録日時</h4></th>
          <th><h4>更新日時</h4></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @children.each do |child| %>
          <tr>
            <td><h5><%= link_to child.childname, child %></h5></td>
            <td><h5><%= child.childbirthday %></h5></td>
            <td><h5><%= child.age %>歳</h5></td>            
            <td><h5><%= child.created_at.strftime('%Y-%m-%d %H:%M') %></h5></td>
            <td><h5><%= child.updated_at.strftime('%Y-%m-%d %H:%M') %></h5></td>
            <td><%= link_to '編集', edit_child_path(child), class: "btn btn-primary" %></td>
            <td><%= link_to '削除', child, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-warning' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
  <% end %>
  
  <%= link_to 'こども登録', new_child_path, class: "btn btn-primary" %>
  <%= link_to 'ことば一覧に移動', childlogs_path, class: "btn btn-default" %>

app/views/children/new.html.erb
<div class="pagetitle">
  <p><h2 align="center">こども登録</h2></p>
  <p><h3 align="center">- ニックネームと誕生日を入力して登録してね -</h3></p>
</div>

<div class="row">
  <div class="col-lg-offset-3 col-lg-6 col-sm-offset-2 col-sm-8 col-xs-12">

<%= form_for(@child) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :childname, 'ニックネーム' %>
    <%= f.text_field :childname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :childbirthday, '誕生日' %>
    <%= f.date_field :childbirthday, value: Time.now.strftime("%Y-%m-%d"),class: 'form-control' %>
  </div>

  <%= f.submit 'こども登録', class: 'btn btn-primary' %>
  <%= link_to 'ことば一覧に移動', childlogs_url , class: 'btn btn-default'%> 
  <% end %>
  </div>
</div>

app/views/children/show.html.erb
<div class="pagetitle">
  <h2 align="center">こどもの詳細</h2>
</div>

<table class="table table-hover">
    <thead.thead-default>
  <tr>
    <th><h4>ニックネーム</h4></th>
    <td><h4><%= @child.childname %></h4></td>
  </tr>
  <tr>
    <th><h4>誕生日</h4></th>
    <td><h4><%= @child.childbirthday %></h4></td>
  </tr>
  <tr>
    <th><h4>年齢</h3></th>
    <td><h4><%= @child.age %>歳</h4></td>
  </tr> 
  <tr>
    <th><h4>登録日時</h4></th>
    <td><h4><%= @child.created_at.strftime('%Y/%m/%d %H:%M') %></h4></td>
  </tr>
  <tr>
    <th><h4>更新日時</h4></th>
    <td><h4><%= @child.updated_at.strftime('%Y/%m/%d %H:%M') %></h4></td>
  </tr>
</table>

<%= link_to '編集', edit_child_path(@child), class: 'btn btn-primary' %>
<%= link_to '削除', @child, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-warning' %>
<%= link_to 'こども一覧に戻る', children_url , class: 'btn btn-default'%> 

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |task_type, task| %>
  <div class="alert alert-<%= task_type %>"><%= task %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 こどもろぐ</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left" href="/"><img src="/images/logo.png" alt="こどもろぐ"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <li><%= link_to 'こども登録', new_child_path %></li>
              <li><%= link_to 'こども一覧', children_path %></li>
              <li><%= link_to 'ことば登録', new_childlog_path %></li>
              <li><%= link_to 'ことば一覧', childlogs_path %></li>
              <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'ユーザー登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>こどもろぐ</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>

<% else %>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 cover-img" style="background-image:url('/images/park_photo2.jpg');">
		<div class="col-xs-12 cover-mask";">			
			<div class="cover-text text-center">
				<h1 style="color: #0904f9;">こどもログにようこそ！</h1>
				<BR>
				  <%= link_to 'ユーザー登録', signup_path, class: 'btn btn-lg btn-primary' %>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-info">
      <div class="panel-heading">ユーザー登録</div>
      <div class="panel-body">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'ニックネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '新規登録', class: 'btn btn-primary btn-block' %>

    <% end %>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Childlogs <span class="badge"><%= @count_childlogs %></span><% end %></li>
    </ul>
       <%= render 'childlogs/childlogs', childlogs: @childlogs %>
  </div>
</div>